// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	Age       int    `json:"age"`
	CountryID string `json:"country_id"`
}

type User struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	Age       int    `json:"age"`
	CountryID string `json:"country_id"`
}

type UserOps struct {
	Create *User `json:"create"`
}
